version: '1'

services:
  db-prenotazione:
    image: postgres:alpine
    container_name: db-prenotazione
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: dbRicerca
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  microservizi_prenotazione:
    image: pievit/microservizi_prenotazione
    build:
      context: .
    container_name: microservizi_prenotazione
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-prenotazione:5432/dbRicerca
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8082:8082"
    depends_on:
      - db-prenotazione